export const keysDataContent = {
  Backquote: { en: ['`', '~'], ru: ['ё', 'Ё'] },
  Digit1: { en: ['1', '!'], ru: ['1', '!'] },
  Digit2: { en: ['2', '@'], ru: ['2', '"'] },
  Digit3: { en: ['3', '#'], ru: ['3', '№'] },
  Digit4: { en: ['4', '$'], ru: ['4', ';'] },
  Digit5: { en: ['5', '%'], ru: ['5', '%'] },
  Digit6: { en: ['6', '^'], ru: ['6', ':'] },
  Digit7: { en: ['7', '&'], ru: ['7', '?'] },
  Digit8: { en: ['8', '*'], ru: ['8', '*'] },
  Digit9: { en: ['9', '('], ru: ['9', '('] },
  Digit0: { en: ['0', ')'], ru: ['0', ')'] },
  Minus: { en: ['-', '_'], ru: ['-', '_'] },
  Equal: { en: ['=', '+'], ru: ['=', '+'] },
  KeyQ: { en: ['q', 'Q'], ru: ['й', 'Й'] },
  KeyW: { en: ['w', 'W'], ru: ['ц', 'Ц'] },
  KeyE: { en: ['e', 'E'], ru: ['у', 'У'] },
  KeyR: { en: ['r', 'R'], ru: ['к', 'К'] },
  KeyT: { en: ['t', 'T'], ru: ['е', 'Е'] },
  KeyY: { en: ['y', 'Y'], ru: ['н', 'Н'] },
  KeyU: { en: ['u', 'U'], ru: ['г', 'Г'] },
  KeyI: { en: ['i', 'I'], ru: ['ш', 'Ш'] },
  KeyO: { en: ['o', 'O'], ru: ['щ', 'Щ'] },
  KeyP: { en: ['p', 'P'], ru: ['з', 'З'] },
  BracketLeft: { en: ['[', '{'], ru: ['х', 'Х'] },
  BracketRight: { en: [']', '}'], ru: ['ъ', 'Ъ'] },
  Backslash: { en: ['\\', '|'], ru: ['\\', '|'] },
  KeyA: { en: ['a', 'A'], ru: ['ф', 'Ф'] },
  KeyS: { en: ['s', 'S'], ru: ['ы', 'Ы'] },
  KeyD: { en: ['d', 'D'], ru: ['в', 'В'] },
  KeyF: { en: ['f', 'F'], ru: ['а', 'А'] },
  KeyG: { en: ['g', 'G'], ru: ['п', 'П'] },
  KeyH: { en: ['h', 'H'], ru: ['р', 'Р'] },
  KeyJ: { en: ['j', 'J'], ru: ['о', 'О'] },
  KeyK: { en: ['k', 'K'], ru: ['л', 'Л'] },
  KeyL: { en: ['l', 'L'], ru: ['д', 'Д'] },
  Semicolon: { en: [';', ':'], ru: ['ж', 'Ж'] },
  Quote: { en: ["'", '"'], ru: ['э', 'Э'] },
  KeyZ: { en: ['z', 'Z'], ru: ['я', 'Я'] },
  KeyX: { en: ['x', 'X'], ru: ['ч', 'Ч'] },
  KeyC: { en: ['c', 'C'], ru: ['с', 'С'] },
  KeyV: { en: ['v', 'V'], ru: ['м', 'М'] },
  KeyB: { en: ['b', 'B'], ru: ['и', 'И'] },
  KeyN: { en: ['n', 'N'], ru: ['т', 'Т'] },
  KeyM: { en: ['m', 'M'], ru: ['ь', 'Ь'] },
  Comma: { en: [',', '<'], ru: ['б', 'Б'] },
  Period: { en: ['.', '>'], ru: ['ю', 'Ю'] },
  Slash: { en: ['/', '?'], ru: ['.', ','] },
};

export const keysSpecialDataContent = {
  Backspace: '⌫',
  Tab: 'Tab',
  Delete: 'Del',
  CapsLock: 'Caps',
  Enter: 'Enter',
  ShiftLeft: 'Shift',
  ShiftRight: 'Shift',
  ArrowUp: '↑',
  ControlLeft: 'Ctrl',
  ControlRight: 'Ctrl',
  MetaLeft: '⊞',
  AltLeft: 'Alt',
  AltRight: 'Alt',
  Space: ' ',
  ArrowLeft: '←',
  ArrowDown: '↓',
  ArrowRight: '→',
};

export const keysArr = ['Backquote', 'Digit1', 'Digit2',
  'Digit3', 'Digit4', 'Digit5', 'Digit6', 'Digit7',
  'Digit8', 'Digit9', 'Digit0', 'Minus', 'Equal',
  'Backspace', 'Tab', 'KeyQ', 'KeyW', 'KeyE',
  'KeyR', 'KeyT', 'KeyY', 'KeyU', 'KeyI', 'KeyO',
  'KeyP', 'BracketLeft', 'BracketRight', 'Backslash',
  'Delete', 'CapsLock', 'KeyA', 'KeyS', 'KeyD',
  'KeyF', 'KeyG', 'KeyH', 'KeyJ', 'KeyK', 'KeyL',
  'Semicolon', 'Quote', 'Enter', 'ShiftLeft', 'Backslash', 'KeyZ',
  'KeyX', 'KeyC', 'KeyV', 'KeyB', 'KeyN', 'KeyM',
  'Comma', 'Period', 'Slash', 'ArrowUp', 'ShiftRight',
  'ControlLeft', 'MetaLeft', 'AltLeft', 'Space', 'AltRight',
  'ControlRight', 'ArrowLeft', 'ArrowDown', 'ArrowRight'];

export const doubleKeysArr = ['Backspace', 'CapsLock', 'Enter', 'ShiftLeft'];

export const spaceContents = {
  Space: { en: [' ', ' '], ru: ['\u00A0', ' '] },
  Tab: { en: ['\ \ \ ', '\ '], ru: ['\ \ \ ', '\ '] }
}
